routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/department', 'DepartmentController');
});

app/OldQuestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OldQuestion extends Model
{
    public function department(){
    	return $this->belongsTo('App\Department');
    }
    public function semester(){
    	return $this->belongsTo('App\Semester');
    }
    public function oldQuestion_file(){
    	return $this->hasMany('App\OldQuestionFile','oldQuestion_id');
    }
}

app/Http/Controllers/Api/v1/OldQuestionController.php
<?php

namespace App\Http\Controllers\Api\v1;

use Validator;
use App\OldQuestion;
use Illuminate\Http\Request;
use App\Traits\AppAuthorization;
use App\Http\Controllers\Controller;
use \Illuminate\Http\Response as Res;

class OldQuestionController extends BaseController
{
    use AppAuthorization;
    public function __construct(Request $request) {
        $this->authorizeToken($request);
    }
    /** 
        *   @OA\get(
        *     path="/oldquestion/filter",
        *     tags={"Search"},
        *     description="old question filter",
        *     summary="old question filter",
        *     security= {{"App_Key":"",}},
        *     @OA\Parameter(name="department", in="query", description="department",
        *          @OA\Schema(type="string",), 
        *      ),
        *     @OA\Parameter(name="semester", in="query", description="semester",
        *          @OA\Schema(type="string",), 
        *      ),
        *     @OA\Response(response=200,description="note filtered successful",
        *         @OA\JsonContent(type="object",
        *         ),
        *         @OA\Link(
        *             link="SearchFilter",
        *             operationId="SearchFilter",
        *             parameters={
        *                   "department":"5",
        *                   "semester":"1",
        *             },
        *          ),
        *     ),
        *     @OA\Response( response="default",description="unexpected error",
        *         @OA\JsonContent(type="object",
        *         ),
        *     ),
        * )
    */
    public function filter(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'department'  => 'required|integer',
            'semester'  => 'required|integer',
        ]);

        if($validator->fails()){
            $this->setStatusCode(Res::HTTP_UNPROCESSABLE_ENTITY);
            return $this->respondValidationError('Validation Error.', $validator->errors());
        }
        $data = OldQuestion::where('department_id',$request->department)
                    ->where('semester_id',$request->semester)
                    ->with('oldQuestion_file')
                    ->orderBy('created_at','desc')
                    ->get();
        if(count($data)<1) {
            $this->setStatusCode(Res::HTTP_NOT_FOUND);
            return $this->respondNotFound('No question found');
        }
        $this->setStatusCode(Res::HTTP_OK);
        return $this->sendSuccessResponse($data, 'question list success');
    }
}

app/Http/Controllers/OldQuestionController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\OldQuestion;
use App\Department;
use App\OldQuestionFile;
use Illuminate\Http\Request;

class OldQuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = OldQuestion::orderBy('id','desc')->paginate(10);
        return view('admin.oldquestion.index',compact('questions'));
    }
    public function getOldQuestionFile(Request $request){
        $data = OldQuestionFile::where('oldQuestion_id',$request->id)->get();
        $response = array(
            'status' => 'success',
            'msg' => $data
        );
        return response()->json($response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('admin.oldquestion.create',compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'department_id' => 'required|integer',
            'semester' => 'required',
            'subject' => 'required',
            'files' => 'required',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = new OldQuestion;
        $data->department_id = $request->department_id;
        $data->semester_id = $request->semester;
        $data->subject = $request->subject;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/oldquestion/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/oldquestion/', $name);  
                $dataFile = new OldQuestionFile;
                $dataFile->oldQuestion_id = $data->id;
                $dataFile->file_title = $title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('question.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question = OldQuestion::find($id);
        $departments = Department::all();
        return view('admin.oldquestion.edit',compact('question','departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'department_id' => 'required|integer',
            'semester' => 'required',
            'subject' => 'required',
            'files' => 'sometimes',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = OldQuestion::find($id);
        $data->department_id = $request->department_id;
        $data->semester_id = $request->semester;
        $data->subject = $request->subject;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/oldquestion/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/oldquestion/', $name);  
                $dataFile = new OldQuestionFile;
                $dataFile->oldQuestion_id = $data->id;
                $dataFile->file_title = $title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('question.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $files = OldQuestionFile::where('oldQuestion_id',$id)->get();
        foreach($files as $file){
            Storage::delete($file->file_name);
            $file->delete();
        }
        OldQuestion::find($id)->delete();
        return redirect()->route('question.index');
    }
    public function deleteOldQuestionFile($id)
    {
        $file = OldQuestionFile::find($id);
        Storage::delete($file->file_name);
        $file->delete();
        return redirect()->back();
    }
}

resources/views/admin/oldquestion/create.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Add Old Question</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('question.store')}}" enctype="multipart/form-data">
                   @csrf
                   <div class="form-group">
                      <label>Department:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="department_id" class="form-control" required>
                            <option value="{{null}}">Select Department</option>
                            @foreach($departments as $department)
                            <option value="{{$department->id}}">{{$department->title}}</option>
                            @endforeach
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Semester:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="semester" class="form-control" required>
                            <option value="{{null}}">Select Semester</option>
                            <option value="{{'1'}}">semester one</option>
                            <option value="{{'2'}}">semester two</option>
                            <option value="{{'3'}}">semester three</option>
                            <option value="{{'4'}}">semester four</option>
                            <option value="{{'5'}}">semester five</option>
                            <option value="{{'6'}}">semester six</option>
                            <option value="{{'7'}}">semester seven</option>
                            <option value="{{'8'}}">semester eight</option>
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Subject:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="subject" placeholder="subject" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Questions:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]" required multiple="multiple">
                      </div>
                   </div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endSection
@section('scripts')
<script>
  
</script>
@endsection

resources/views/admin/oldquestion/edit.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Edit Note</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('question.update',$question->id)}}" enctype="multipart/form-data">
                   @csrf
                   @method('PUT')
                   <div class="form-group">
                      <label>Department:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="department_id" class="form-control" required>
                            <option value="{{null}}">Select Department</option>
                            @foreach($departments as $department)
                            <option value="{{$department->id}}" @if($question->department_id==$department->id) selected @endif>{{$department->title}}</option>
                            @endforeach
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Semester:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="semester" class="form-control" required>
                            <option value="{{null}}">Select Semester</option>
                            <option value="{{'1'}}" @if($question->semester_id=='1') selected @endif>semester one</option>
                            <option value="{{'2'}}" @if($question->semester_id=='2') selected @endif>semester two</option>
                            <option value="{{'3'}}" @if($question->semester_id=='3') selected @endif>semester three</option>
                            <option value="{{'4'}}" @if($question->semester_id=='4') selected @endif>semester four</option>
                            <option value="{{'5'}}"@if($question->semester_id=='5') selected @endif>semester five</option>
                            <option value="{{'6'}}"@if($question->semester_id=='6') selected @endif>semester six</option>
                            <option value="{{'7'}}"@if($question->semester_id=='7') selected @endif>semester seven</option>
                            <option value="{{'8'}}"@if($question->semester_id=='8') selected @endif>semester eight</option>
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Subject:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="subject" id="subject" placeholder="subject" value="{{$question->subject}}" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Notes:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]" multiple="multiple">
                      </div>
                   </div>
                   <div id="file-action" class="row"></div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>

@endSection
@section('scripts')
<script>

  $(document).ready(function(){
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    var data = $('#subject').val();
    if(data){
      $.ajax({
          url: '{{route('ajaxGetOldQuestionFile')}}',
          data:{
              _token: CSRF_TOKEN,
              id: <?php echo $question->id; ?>,
          },
          dataType: 'JSON',
          success:function(data){
              console.log(data.msg)
              var files = data.msg
              $('#file-action').html('');
              $.each(files, function(index, value){
                  $('#file-action').append('<div class="col-md-2">'+(value.file_title)+'<form method="post" action="/oldquestionfile/'+(value.id)+'/delete">@csrf @method("DELETE")<button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>');
                  // $('#file-action').append($('<option>',{value:value.id}).text(value.name));
                  console.log(value);
              });
          }
      })
    }
  })
</script>
@endsection

resources/views/admin/oldquestion/index.blade.php
@extends('layouts.app')
@section('styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection
@section('content')
<script src="{{asset('adminlte/bower_components/ckeditor/ckeditor.js')}}"></script>
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-10">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Old Question</h3>
                <div class="pull-right">
                <a href="{{route('question.create')}}" class="btn btn-xs btn-primary">Add Old Question</a>
                </div>
              </div>
              <div class="box-body">
                <table id="dataTable" class="table table-bordered table-hover">
                  <thead>
                   <tr>
                    <th>SN</th>
                    <th>Department</th>
                    <th>Semester</th>
                    <th>Subject</th>
                    <th>File</th>
                    <th>Action</th>
                  </tr>
                 </thead>
                 <tbody>
                 @foreach($questions as $k=>$question)
                 <tr>
                   <td>{{$k+1}}</td>
                   <td>{{$question->department->title}}</td>
                   <td>{{$question->semester->title}}</td>
                   <td>{{$question->subject}}</td>
                   <td>
                     @foreach($question->oldQuestion_file as $file)
                      <li>
                        <a href="{{asset($file->file_name)}}">{{$file->file_title}}</a>
                      </li>
                     @endforeach
                   </td>
                   <td>
                     <form action="{{route('question.destroy',$question->id)}}" method="post">
                     <a href="{{route('question.edit',$question->id)}}" class="btn btn-xs btn-warning">EDIT</a>
                      @csrf 
                      @method('DELETE')
                      <input type="submit" class="btn btn-xs btn-danger" value="DELETE">
                     </form>
                   </td>
                 </tr>
                 @endforeach
                 </tbody>
               </table>
               <div class="text-center">
                 {{ $questions->links() }}
               </div>  
            </div>
        </div>
    </div>
  </div>
</div>
@endSection
@section('scripts')
<script src="{{asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
//data table
    $('#dataTable').DataTable({
      'paging'      : false,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : false
    });
</script>
@endsection