routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/department', 'DepartmentController');
});

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
	public function department(){
    	return $this->belongsTo('App\Department');
    }
    public function semester(){
    	return $this->belongsTo('App\Semester');
    }
    public function note_file(){
    	return $this->hasMany('App\NoteFile');
    }
}

app/Http/Controllers/Api/v1/NoteController.php
<?php

namespace App\Http\Controllers\Api\v1;

use Auth;
use App\Note;
use Validator;
use Illuminate\Http\Request;
use App\Traits\AppAuthorization;
use App\Http\Controllers\Controller;
use \Illuminate\Http\Response as Res;

class NoteController extends BaseController
{
	use AppAuthorization;
    public function __construct(Request $request) {
        $this->authorizeToken($request);
    }
	/** 
        *   @OA\get(
        *     path="/note/filter",
        *     tags={"Search"},
        *     description="Note filter",
        *     summary="Note filter",
        *     security= {{"App_Key":"",}},
        *     @OA\Parameter(name="department", in="query", description="department",
        *          @OA\Schema(type="string",), 
        *      ),
        *     @OA\Parameter(name="semester", in="query", description="semester",
        *          @OA\Schema(type="string",), 
        *      ),
        *     @OA\Response(response=200,description="note filtered successful",
        *         @OA\JsonContent(type="object",
        *         ),
        *         @OA\Link(
        *             link="SearchFilter",
        *             operationId="SearchFilter",
        *             parameters={
        *                   "department":"5",
        *                   "semester":"semester one",
        *             },
        *          ),
        *     ),
        *     @OA\Response( response="default",description="unexpected error",
        *         @OA\JsonContent(type="object",
        *         ),
        *     ),
        * )
    */
    public function filter(Request $request)
    {
    	$validator = Validator::make($request->all(), [
            'department'  => 'required|integer',
            'semester'  => 'required|integer',
        ]);

        if($validator->fails()){
            $this->setStatusCode(Res::HTTP_UNPROCESSABLE_ENTITY);
            return $this->respondValidationError('Validation Error.', $validator->errors());
        }
    	$data = Note::where('department_id',$request->department)
    				->where('semester_id',$request->semester)
    				->with('note_file')
    				->get();
    	if(count($data)<1) {
            $this->setStatusCode(Res::HTTP_NOT_FOUND);
            return $this->respondNotFound('No note matched your query');
        }
        $this->setStatusCode(Res::HTTP_OK);
        return $this->sendSuccessResponse($data, 'note list success');
    }
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Note;
use App\Department;
use App\NoteFile;
use Illuminate\Http\Request;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Note::orderBy('id','desc')->paginate(10);
        return view('admin.note.index',compact('notes'));
    }
    public function getNoteFile(Request $request){
        $data = NoteFIle::where('note_id',$request->id)->get();
        $response = array(
            'status' => 'success',
            'msg' => $data
        );
        return response()->json($response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('admin.note.create',compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'department_id' => 'required|integer',
            'semester' => 'required',
            'subject' => 'required',
            'files' => 'required',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = new Note;
        $data->department_id = $request->department_id;
        $data->semester_id = $request->semester;
        $data->subject = $request->subject;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/notes/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/notes/', $name);  
                $dataFile = new NoteFile;
                $dataFile->note_id = $data->id;
                $dataFile->title = $title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('note.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $note = Note::find($id);
        $departments = Department::all();
        return view('admin.note.edit',compact('note','departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'department_id' => 'required|integer',
            'semester' => 'required',
            'subject' => 'required',
            'files' => 'sometimes',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = Note::find($id);
        $data->department_id = $request->department_id;
        $data->semester_id = $request->semester;
        $data->subject = $request->subject;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/notes/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/notes/', $name);  
                $dataFile = new NoteFile;
                $dataFile->note_id = $data->id;
                $dataFile->title = $title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('note.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $files = NoteFile::where('note_id',$id)->get();
        foreach($files as $file){
            Storage::delete($file->file_name);
            $file->delete();
        }
        Note::find($id)->delete();
        return redirect()->route('note.index');
    }
    public function deleteNoteFile($id)
    {
        $file = NoteFile::find($id);
        Storage::delete($file->file_name);
        $file->delete();
        return redirect()->back();
    }
}

resources/views/admin/note/create.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Add Department</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('note.store')}}" enctype="multipart/form-data">
                   @csrf
                   <div class="form-group">
                      <label>Department:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="department_id" class="form-control" required>
                            <option value="{{null}}">Select Department</option>
                            @foreach($departments as $department)
                            <option value="{{$department->id}}">{{$department->title}}</option>
                            @endforeach
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Semester:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="semester" class="form-control" required>
                            <option value="{{null}}">Select Semester</option>
                            <option value="{{'1'}}">semester one</option>
                            <option value="{{'2'}}">semester two</option>
                            <option value="{{'3'}}">semester three</option>
                            <option value="{{'4'}}">semester four</option>
                            <option value="{{'5'}}">semester five</option>
                            <option value="{{'6'}}">semester six</option>
                            <option value="{{'7'}}">semester seven</option>
                            <option value="{{'8'}}">semester eight</option>
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Subject:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="subject" placeholder="subject" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Notes:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]" required multiple="multiple">
                      </div>
                   </div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endSection
@section('scripts')
<script>
  
</script>
@endsection

resources/views/admin/note/edit.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Edit Note</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('note.update',$note->id)}}" enctype="multipart/form-data">
                   @csrf
                   @method('PUT')
                   <div class="form-group">
                      <label>Department:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="department_id" class="form-control" required>
                            <option value="{{null}}">Select Department</option>
                            @foreach($departments as $department)
                            <option value="{{$department->id}}" @if($note->department_id==$department->id) selected @endif>{{$department->title}}</option>
                            @endforeach
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Semester:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <select name="semester" class="form-control" required>
                            <option value="{{null}}">Select Semester</option>
                            <option value="{{'1'}}" @if($note->semester_id=='1') selected @endif>semester one</option>
                            <option value="{{'2'}}" @if($note->semester_id=='2') selected @endif>semester two</option>
                            <option value="{{'3'}}" @if($note->semester_id=='3') selected @endif>semester three</option>
                            <option value="{{'4'}}" @if($note->semester_id=='4') selected @endif>semester four</option>
                            <option value="{{'5'}}"@if($note->semester_id=='5') selected @endif>semester five</option>
                            <option value="{{'6'}}"@if($note->semester_id=='6') selected @endif>semester six</option>
                            <option value="{{'7'}}"@if($note->semester_id=='7') selected @endif>semester seven</option>
                            <option value="{{'8'}}"@if($note->semester_id=='8') selected @endif>semester eight</option>
                          </select>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Subject:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="subject" id="subject" placeholder="subject" value="{{$note->subject}}" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Notes:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]" multiple="multiple">
                      </div>
                   </div>
                   <div id="file-action" class="row"></div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>

@endSection
@section('scripts')
<script>

  $(document).ready(function(){
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    var data = $('#subject').val();
    if(data){
      $.ajax({
          url: '{{route('ajaxGetNoteFile')}}',
          data:{
              _token: CSRF_TOKEN,
              id: <?php echo $note->id; ?>,
          },
          dataType: 'JSON',
          success:function(data){
              console.log(data.msg)
              var files = data.msg
              $('#file-action').html('');
              $.each(files, function(index, value){
                  $('#file-action').append('<div class="col-md-2">'+(value.title)+'<form method="post" action="/notefile/'+(value.id)+'/delete">@csrf @method("DELETE")<button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>');
                  // $('#file-action').append($('<option>',{value:value.id}).text(value.name));
                  console.log(value);
              });
          }
      })
    }
  })
</script>
@endsection

resources/views/admin/note/index.blade.php
@extends('layouts.app')
@section('styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection
@section('content')
<script src="{{asset('adminlte/bower_components/ckeditor/ckeditor.js')}}"></script>
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-10">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Note</h3>
                <div class="pull-right">
                <a href="{{route('note.create')}}" class="btn btn-xs btn-primary">Add Note</a>
                </div>
              </div>
              <div class="box-body">
                <table id="dataTable" class="table table-bordered table-hover">
                  <thead>
                   <tr>
                    <th>SN</th>
                    <th>Department</th>
                    <th>Semester</th>
                    <th>Subject</th>
                    <th>Note</th>
                    <th>Action</th>
                  </tr>
                 </thead>
                 <tbody>
                 @foreach($notes as $k=>$note)
                 <tr>
                   <td>{{$k+1}}</td>
                   <td>{{$note->department->title}}</td>
                   <td>{{$note->semester->title}}</td>
                   <td>{{$note->subject}}</td>
                   <td>
                     @foreach($note->note_file as $file)
                      <li>
                        <a href="{{asset($file->file_name)}}">{{$file->title}}</a>
                      </li>
                     @endforeach
                   </td>
                   <td>
                     <form action="{{route('note.destroy',$note->id)}}" method="post">
                     <a href="{{route('note.edit',$note->id)}}" class="btn btn-xs btn-warning">EDIT</a>
                      @csrf 
                      @method('DELETE')
                      <input type="submit" class="btn btn-xs btn-danger" value="DELETE">
                     </form>
                   </td>
                 </tr>
                 @endforeach
                 </tbody>
               </table>
               <div class="text-center">
                 {{ $notes->links() }}
               </div>  
            </div>
        </div>
    </div>
  </div>
</div>
@endSection
@section('scripts')
<script src="{{asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
//data table
    $('#dataTable').DataTable({
      'paging'      : false,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : false
    });
</script>
@endsection