routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/department', 'DepartmentController');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  @include('layouts.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('layouts.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->
  @include('layouts.foot')
  @yield('scripts')
</body>
</html>

resources/views/layouts/foot.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.13
  </div>
  <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
  reserved.
</footer>
</div>
<!-- ./wrapper -->
<!-- jQuery 3 -->
<script src="{{asset('adminlte/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('adminlte/bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.min.js')}}"></script>

resources/views/layouts/head.blade.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Agriculture App</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/skins/_all-skins.min.css')}}">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/layouts/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="javascript:void(0)" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>pp</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Agro</b>App</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
            <span class="hidden-xs">{{Auth::user()->name}}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

              <p>
                {{Auth::user()->name}}
                {{-- <small>Member since Nov. 2012</small> --}}
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-right">
                <a class="btn btn-default btn-flat" href="{{ route('logout') }}"
                      onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">
                      {{ __('Logout') }}
                  </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{{Auth::user()->name}}</p>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">s
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="{{route('department.index')}}">
          <i class="fa fa-building"></i> <span>Department</span>
        </a>
      </li>
      <li>
        <a href="{{route('notice.index')}}">
          <i class="fa fa-th"></i> <span>Notices</span>
        </a>
      </li>
      <li>
        <a href="{{route('note.index')}}">
          <i class="fa fa-th"></i> <span>Notes</span>
        </a>
      </li>
      <li>
        <a href="{{route('result.index')}}">
          <i class="fa fa-th"></i> <span>Result</span>
        </a>
      </li>
      <li>
        <a href="{{route('syllabi.index')}}">
          <i class="fa fa-th"></i> <span>Syllabus</span>
        </a>
      </li>
      <li>
        <a href="{{route('contact.index')}}">
          <i class="fa fa-th"></i> <span>Contact</span>
        </a>
      </li>
      <li>
        <a href="{{route('question.index')}}">
          <i class="fa fa-th"></i> <span>OldQuestion</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>